#include "bloomfilter.h"
#include "../base58.h"
#include <cstring>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <fstream>
#include <sstream>
#include <algorithm>
#include <cctype>
#include <sys/stat.h>

// ================================================================
//  Known address database files
// ================================================================
const AddressFileInfo ADDR_FILES[] = {
    {
        "https://github.com/Pymmdrza/Rich-Address-Wallet/releases/download/Bitcoin/Latest_Rich_Bitcoin_Address.txt.gz",
        "Latest_Rich_Bitcoin_Address.txt.gz",
        "Pymmdrza Rich Bitcoin Address List"
    }
};
const int NUM_ADDR_FILES = sizeof(ADDR_FILES) / sizeof(ADDR_FILES[0]);

// ================================================================
//  MurmurHash3 finalizer for bloom filter hashing
// ================================================================
static inline uint64_t murmur_mix(uint64_t h) {
    h ^= h >> 33;
    h *= 0xff51afd7ed558ccdULL;
    h ^= h >> 33;
    h *= 0xc4ceb9fe1a85ec53ULL;
    h ^= h >> 33;
    return h;
}

// ================================================================
//  BloomFilter implementation
// ================================================================
BloomFilter::BloomFilter()
    : bits_(nullptr), num_bits_(0), num_words_(0), num_hashes_(0), count_(0) {}

BloomFilter::~BloomFilter() {
    delete[] bits_;
}

void BloomFilter::init(uint64_t expected_elements, double fpr) {
    if (expected_elements == 0) expected_elements = 1;
    if (!(fpr > 0.0) || fpr >= 1.0) fpr = 1e-8;

    // Probe budget. k=20 keeps a probe to a handful of iterations — the loop
    // exits at the first clear bit, so a non-member costs ~1/(1-density) steps
    // rather than k — while leaving the block only about a third full at the
    // bit budgets below. A higher k just crowds the 512-bit block: once the
    // block is dense, extra probes buy almost nothing.
    const uint32_t k = BLOOM_DEFAULT_NUM_HASHES;

    // Blocked-filter sizing.
    //
    // Every one of the k bits lands inside a single 512-bit block, so a query
    // passes iff its block is dense enough in exactly those places:
    //     fpr = (1 - exp(-k / beta))^k     with beta = m / n
    // Solving for beta gives the bits per element we actually need. The classic
    // m = -n*ln(p)/ln(2)^2 assumes the k bits are scattered over the WHOLE
    // array; with a blocked layout it under-states the memory needed (and it
    // optimised k for a value we then had to cap anyway), so size from the
    // blocked equation instead.
    double pk = pow(fpr, 1.0 / k);
    if (pk >= 1.0) pk = 0.9999999999999999;   // fpr very close to 1
    double beta = -(double)k / log(1.0 - pk);
    double m = (double)expected_elements * beta;

    // Round the BLOCK COUNT up to a power of two so the device can mask instead
    // of dividing. The >= 512 floor keeps a tiny filter from having zero blocks.
    uint64_t blocks = 1;
    while (blocks < (UINT64_MAX >> 9) && (double)blocks * 512.0 < m) blocks <<= 1;

    init_explicit(blocks * 512, k);
}

void BloomFilter::init_explicit(uint64_t num_bits, uint32_t num_hashes) {
    // Ensure a power of 2 that is at least one 512-bit block. Power-of-2 sizing
    // makes block selection a mask, and the >= 512 floor guarantees at least one
    // block so tiny custom address files cannot underflow the block count.
    uint64_t n = 512;
    while (n < num_bits) n <<= 1;
    num_bits_ = n;
    num_words_ = n / 64;
    num_hashes_ = num_hashes;
    count_ = 0;

    delete[] bits_;
    bits_ = new uint64_t[num_words_]();
    memset(bits_, 0, num_words_ * sizeof(uint64_t));
}

// Blocked bloom filter index computation.
//
// h1 selects one 512-bit block (8 consecutive 64-bit words = one cache line);
// all k bits for this element land inside that single block, so a probe is one
// cache-line load instead of k scattered global loads. The GPU kernel in
// gpu_worker.cu mirrors this bit-for-bit.
//
// The k positions inside the block are generated by an independent mixing
// step per position, NOT by the usual double-hashing arithmetic progression
// `base + i*stride`. That progression is fine for an unblocked filter — the
// positions span the whole array, so there are m^2 distinct index-tuples — but
// inside a block the positions are only taken mod 512, so the ENTIRE tuple
// collapses to (base, stride) with at most 512*512 = 262144 possibilities.
// Every element in a block therefore shares its tuple with one element in
// ~262144/lambda of them, and the false-positive rate floors at lambda/262144
// (lambda = elements per block) — around 1e-4 here, six orders of magnitude
// above target, and unreachable no matter how large the filter grows. Worse,
// because h2 was forced odd, any two of those progressions were translates of
// each other by an even offset, so their overlaps were forced even and the k
// probes were not even independent samples: measured 8.4e-2.
//
// Mixing each position separately gives ~2^64 distinct tuples (the seed is a
// full 64-bit hash of the element), so collisions become negligible and the
// filter behaves like density^k again. It costs two multiplies per position
// tested, and the loop still exits at the first clear bit — a non-member
// averages ~1/(1-density) positions, i.e. a couple of mixes against the
// thousand-plus cycles the hash160 already costs.
void BloomFilter::compute_indices(const uint8_t h160[20], uint64_t *indices) const {
    uint64_t a, b;
    memcpy(&a, h160, 8);
    memcpy(&b, h160 + 8, 8);
    // Additional entropy from remaining 4 bytes
    uint32_t c;
    memcpy(&c, h160 + 16, 4);
    a ^= (uint64_t)c << 32;

    uint64_t h1   = murmur_mix(a);   // selects the block
    uint64_t seed = murmur_mix(b);   // generates the positions inside it

    uint64_t block_mask = (num_bits_ >> 9) - 1;      // num_blocks - 1 (power of 2)
    uint64_t base_bit   = (h1 & block_mask) << 9;    // block start, as a bit index

    uint64_t x = seed;
    for (uint32_t i = 0; i < num_hashes_; i++) {
        x += 0x9E3779B97F4A7C15ULL;                  // splitmix64 stream
        uint64_t z = x;
        z ^= z >> 30; z *= 0xBF58476D1CE4E5B9ULL;
        z ^= z >> 27; z *= 0x94D049BB133111EBULL;
        z ^= z >> 31;
        // Absolute bit index = block start + within-block position. Must be
        // addition, not OR: the position spans 9 bits and would collide with
        // the block's low bits. insert()/test() split this back into a word
        // (>>6) and an offset (&63), which matches the device's
        // word_base + (bit>>6) decomposition.
        indices[i] = base_bit + (z & 511u);
    }
}

void BloomFilter::insert(const uint8_t h160[20]) {
    uint64_t indices[30];
    compute_indices(h160, indices);
    for (uint32_t i = 0; i < num_hashes_; i++) {
        uint64_t bit = indices[i];
        bits_[bit >> 6] |= (1ULL << (bit & 63));
    }
    
    std::array<uint8_t, 20> arr;
    memcpy(arr.data(), h160, 20);
    exact_hashes_.push_back(arr);
    
    count_++;
}

void BloomFilter::sort_exact() {
    std::sort(exact_hashes_.begin(), exact_hashes_.end());
}

bool BloomFilter::exact_test(const uint8_t h160[20]) const {
    std::array<uint8_t, 20> arr;
    memcpy(arr.data(), h160, 20);
    return std::binary_search(exact_hashes_.begin(), exact_hashes_.end(), arr);
}

bool BloomFilter::test(const uint8_t h160[20]) const {
    uint64_t indices[30];
    compute_indices(h160, indices);
    for (uint32_t i = 0; i < num_hashes_; i++) {
        uint64_t bit = indices[i];
        if (!(bits_[bit >> 6] & (1ULL << (bit & 63)))) return false;
    }
    return true;
}

// ================================================================
//  Base58 decode (local, for address loading)
// ================================================================
static const char B58_CHARS[] = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";

// Alphabet -> value, -1 for every character not in it. Built once.
static const int8_t *base58_map() {
    static int8_t map[256];
    static const bool ready = [] {
        memset(map, -1, sizeof(map));
        for (int i = 0; i < 58; i++) map[(uint8_t)B58_CHARS[i]] = (int8_t)i;
        return true;
    }();
    (void)ready;
    return map;
}

// Decode str[begin..] from base58 into `buf` as a big-endian number that is
// right-aligned (buf[buf_size-1] is the least significant byte). Returns the
// number of significant bytes through *out_len, false on an invalid character
// or if the value does not fit.
//
// Each new most-significant byte is a single store at the front of the value.
// The previous version grew a std::vector and called insert(result.begin(),
// ...) for every such byte, which shifted the whole payload on every character
// — O(len^2) per address, on the hot path while loading a multi-million line
// address file.
static bool base58_decode_value(const std::string &str, size_t begin,
                                uint8_t *buf, size_t buf_size, size_t *out_len) {
    const int8_t *map = base58_map();
    memset(buf, 0, buf_size);
    size_t n = 0;   // significant bytes, right-aligned at the end of buf

    for (size_t i = begin; i < str.size(); i++) {
        int carry = map[(uint8_t)str[i]];
        if (carry < 0) return false;
        for (size_t j = 0; j < n; j++) {
            int x = buf[buf_size - 1 - j] * 58 + carry;
            buf[buf_size - 1 - j] = (uint8_t)x;
            carry = x >> 8;
        }
        if (carry) {
            // carry <= 57 always (255*58 + 57 = 14847 < 2^14), so it is one byte.
            if (n == buf_size) return false;
            buf[buf_size - 1 - n] = (uint8_t)carry;
            n++;
        }
    }
    *out_len = n;
    return true;
}

static bool decode_base58check_h160(const std::string &addr, uint8_t h160[20]) {
    // A leading '1' is one zero byte of payload. Those digits are processed
    // while the accumulator is still empty, so they add nothing to the value:
    // count them, decode the rest, then re-apply them as byte padding.
    size_t pad = 0;
    while (pad < addr.size() && addr[pad] == '1') pad++;

    uint8_t buf[40];
    size_t n;
    if (!base58_decode_value(addr, pad, buf, sizeof(buf), &n)) return false;

    // Padded layout is [0, pad) zero bytes followed by the n significant bytes,
    // and a P2PKH/P2SH payload is always exactly 25 of them.
    if (pad + n != 25) return false;

    uint8_t full[25];
    memset(full, 0, pad);
    memcpy(full + pad, buf + (sizeof(buf) - n), n);

    // Version byte must be a mainnet P2PKH (0x00) or P2SH (0x05) payload,
    // otherwise the 20 bytes that follow are not a hash160.
    if (full[0] != 0x00 && full[0] != 0x05) return false;

    memcpy(h160, full + 1, 20);
    return true;
}

// ================================================================
//  Bech32 decode
// ================================================================
static const char BECH32_CHARSET[] = "qpzry9x8gf2tvdw0s3jn54khce6mua7l";

bool bech32_decode_to_program(const std::string &addr, std::vector<uint8_t> &program, int &witver) {
    size_t pos = addr.rfind('1');
    if (pos == std::string::npos || pos < 1 || pos + 7 > addr.size()) return false;

    std::string data_part = addr.substr(pos + 1);

    int8_t charset_rev[128];
    memset(charset_rev, -1, sizeof(charset_rev));
    for (int i = 0; i < 32; i++) charset_rev[(uint8_t)BECH32_CHARSET[i]] = i;

    std::vector<int> data;
    for (char c : data_part) {
        char cl = (c >= 'A' && c <= 'Z') ? (c + 32) : c;
        if ((uint8_t)cl >= 128 || charset_rev[(uint8_t)cl] < 0) return false;
        data.push_back(charset_rev[(uint8_t)cl]);
    }

    if (data.size() < 8) return false;

    witver = data[0];
    std::vector<int> five_bit(data.begin() + 1, data.end() - 6);

    int acc = 0, bits = 0;
    program.clear();
    for (int val : five_bit) {
        acc = (acc << 5) | val;
        bits += 5;
        while (bits >= 8) {
            bits -= 8;
            program.push_back((acc >> bits) & 0xFF);
        }
    }

    return program.size() >= 20;
}

// ================================================================
//  Unified address decoder
// ================================================================
bool decode_address_to_h160(const std::string &addr, uint8_t h160[20]) {
    if (addr.empty()) return false;

    // P2PKH (1xxx) or P2SH (3xxx)
    if (addr[0] == '1' || addr[0] == '3') {
        return decode_base58check_h160(addr, h160);
    }

    // Bech32 (bc1q for P2WPKH, bc1p for P2TR)
    std::string lower = addr;
    for (auto &c : lower) c = (char)tolower((unsigned char)c);

    if (lower.substr(0, 3) == "bc1") {
        std::vector<uint8_t> program;
        int witver;
        if (!bech32_decode_to_program(lower, program, witver)) return false;

        if (witver == 0 && program.size() == 20) {
            // P2WPKH: witness program IS the hash160 of the compressed pubkey.
            memcpy(h160, program.data(), 20);
            return true;
        }
        // P2TR (witver 1, 32-byte program) and any other witness version are not
        // hash160s. Inserting a truncated 20-byte "proxy" only added unmatchable
        // noise that raised the false-positive rate, so reject them here.
    }

    return false;
}

// ================================================================
//  File download
// ================================================================
static bool file_exists(const std::string &path) {
    struct stat st;
    return stat(path.c_str(), &st) == 0;
}

bool download_address_file(const std::string &filename, const std::string &url) {
    // Check if already decompressed
    std::string txt_name = filename;
    if (txt_name.size() > 3 && txt_name.substr(txt_name.size() - 3) == ".gz") {
        txt_name = txt_name.substr(0, txt_name.size() - 3);
    }

    if (file_exists(txt_name)) {
        printf("  [✓] %s already exists, skipping download.\n", txt_name.c_str());
        return true;
    }

    if (file_exists(filename)) {
        printf("  [✓] %s already exists (compressed), decompressing...\n", filename.c_str());
    } else {
        printf("  [↓] Downloading %s ...\n", filename.c_str());
        fflush(stdout);

        std::string cmd = "wget -q --show-progress -O \"" + filename + "\" \"" + url + "\"";
        int ret = system(cmd.c_str());
        if (ret != 0) {
            // Try curl as fallback
            cmd = "curl -L --progress-bar -o \"" + filename + "\" \"" + url + "\"";
            ret = system(cmd.c_str());
            if (ret != 0) {
                fprintf(stderr, "  [!] Failed to download %s\n", filename.c_str());
                return false;
            }
        }
    }

    // Decompress if .gz
    if (filename.size() > 3 && filename.substr(filename.size() - 3) == ".gz") {
        printf("  [⚙] Decompressing %s ...\n", filename.c_str());
        fflush(stdout);
        std::string cmd = "gunzip -kf \"" + filename + "\"";
        int ret = system(cmd.c_str());
        if (ret != 0) {
            fprintf(stderr, "  [!] Failed to decompress %s\n", filename.c_str());
            return false;
        }
    }

    return true;
}

// ================================================================
//  Load addresses into bloom filter
// ================================================================

// Pull the address field out of a line: "address", "address\tbalance",
// "address,balance", "address balance" or a quoted variant of any of those.
static bool extract_addr(const std::string &line, std::string &addr) {
    size_t tab = line.find('\t');
    size_t comma = line.find(',');
    size_t space = line.find(' ');

    if (tab != std::string::npos && (comma == std::string::npos || tab < comma)) {
        addr.assign(line, 0, tab);
    } else if (comma != std::string::npos && (space == std::string::npos || comma < space)) {
        addr.assign(line, 0, comma);
    } else if (space != std::string::npos) {
        addr.assign(line, 0, space);
    } else {
        addr = line;
    }

    while (!addr.empty() && (addr.back() == ' ' || addr.back() == '"'))
        addr.pop_back();
    while (!addr.empty() && (addr.front() == ' ' || addr.front() == '"'))
        addr.erase(addr.begin());

    return !addr.empty();
}

// True only for address types an ENABLED search can actually match, so that
// disabled types (and unmatchable ones such as bc1p) add no set bits to the
// filter and therefore do not raise its false-positive rate.
struct TypeWants {
    bool compressed;    // P2PKH(c) + P2WPKH
    bool uncompressed;  // P2PKH(u)
    bool p2sh;          // P2SH-P2WPKH
    bool p2pkh;         // any 1xxx hash160
};

static TypeWants wants_for(uint32_t type_mask) {
    TypeWants w;
    w.compressed   = (type_mask & 0x1u) != 0;
    w.uncompressed = (type_mask & 0x2u) != 0;
    w.p2sh         = (type_mask & 0x4u) != 0;
    w.p2pkh        = w.compressed || w.uncompressed;
    return w;
}

static bool address_type_relevant(const std::string &addr, const TypeWants &w) {
    char c0 = addr[0];
    if (c0 == '1') return w.p2pkh;
    if (c0 == '3') return w.p2sh;
    // bc1q P2WPKH: its witness program IS hash160(compressed pubkey), so the
    // compressed search matches it with no extra work.
    if ((c0 == 'b' || c0 == 'B') && addr.size() >= 4 &&
        (addr[1] == 'c' || addr[1] == 'C') && addr[2] == '1' &&
        (addr[3] == 'q' || addr[3] == 'Q')) return w.compressed;
    return false;   // bc1p (P2TR) and anything else: unmatchable
}

// Count how many addresses in the file would be inserted for `type_mask`,
// without touching a filter. The caller sizes the filter from this instead of
// from a fixed guess: guessing 200M for a file that holds ~30M allocates 4x the
// device memory and spreads the same bits across 4x the address space, which
// makes every probe walk a much larger and much colder array for no benefit.
// A line whose address fails to decode is counted here but not inserted later,
// which only makes the filter more conservative (fewer elements, lower FPR).
uint64_t count_addresses_in_file(const std::string &filepath, uint32_t type_mask) {
    std::ifstream fin(filepath);
    if (!fin) {
        fprintf(stderr, "  [!] Cannot open %s\n", filepath.c_str());
        return 0;
    }

    const TypeWants w = wants_for(type_mask);
    std::string line, addr;
    uint64_t n = 0;
    uint64_t line_no = 0;

    while (std::getline(fin, line)) {
        line_no++;
        if (line.empty() || line[0] == '#') continue;
        while (!line.empty() && (line.back() == '\r' || line.back() == '\n'))
            line.pop_back();
        if (!extract_addr(line, addr)) continue;
        if (address_type_relevant(addr, w)) n++;

        if (line_no % 5000000 == 0) {
            printf("\r  Counting: %llu lines, %llu addresses",
                   (unsigned long long)line_no, (unsigned long long)n);
            fflush(stdout);
        }
    }
    printf("\r  Counted %llu matchable addresses in %llu lines          \n",
           (unsigned long long)n, (unsigned long long)line_no);
    return n;
}

uint64_t load_addresses_to_bloom(const std::string &filepath, BloomFilter &bf,
                                 uint32_t type_mask) {
    std::ifstream fin(filepath);
    if (!fin) {
        fprintf(stderr, "  [!] Cannot open %s\n", filepath.c_str());
        return 0;
    }

    const TypeWants w = wants_for(type_mask);
    std::string line, addr;
    uint64_t loaded = 0;
    uint64_t skipped = 0;
    uint64_t line_no = 0;

    while (std::getline(fin, line)) {
        line_no++;

        // Skip empty lines and comments
        if (line.empty() || line[0] == '#') continue;

        // Trim CR/LF
        while (!line.empty() && (line.back() == '\r' || line.back() == '\n'))
            line.pop_back();

        if (!extract_addr(line, addr)) continue;

        if (!address_type_relevant(addr, w)) { skipped++; continue; }

        uint8_t h160[20];
        if (decode_address_to_h160(addr, h160)) {
            bf.insert(h160);
            loaded++;
        } else {
            skipped++;
        }

        if (line_no % 1000000 == 0) {
            printf("\r  Loading: %llu lines, %llu addresses, %llu skipped",
                   (unsigned long long)line_no, (unsigned long long)loaded,
                   (unsigned long long)skipped);
            fflush(stdout);
        }
    }

    printf("\r  Loaded %llu addresses from %llu lines (%llu skipped)          \n",
           (unsigned long long)loaded, (unsigned long long)line_no,
           (unsigned long long)skipped);

    return loaded;
}
